# Reading the Data...
targated_distance = int(input())

minute_per_km = 2
# Calculating Required Time...
required_time = targated_distance * minute_per_km
# Printing the results...
print('{0} minutos'.format(required_time))
