# Reading Data...
spent_time = int(input())
average_speed = int(input())

# Calculating Fuel Consumption...
fuel_spent = (spent_time * average_speed) / 12
# Printing the results...
print('{0:.3f}'.format(fuel_spent))
