# Reading the Data...
N = int(input())

# Calculating the results...

# For Seconds...
seconds = int(N % 60.0)

# For Minutes...
accumulated_minutes = int(N / 60.0)
minutes = int(accumulated_minutes % 60.0)

# For Hours...
hours = int(accumulated_minutes / 60.0)

# Printing Results...
print('{0}:{1}:{2}'.format(hours, minutes, seconds))
