# Reading the User Inputs...
first_number, second_number, third_number = input().split(' ')

# Checking between first two numbers...
great = (int(first_number) + int(second_number) +
         abs(int(first_number) - int(second_number))) / 2
# Checking with the last number...
greatest = (int(great) + int(third_number) +
            abs(int(great) - int(third_number))) / 2
# Printing the results...
print('{0} eh o maior'.format(int(greatest)))
