# Reading the Values...
A, B, C = input().split(' ')

PI = 3.14159

# Area of Triangle...
area_of_triangle = (1.0 / 2) * float(A) * float(C)
# Area of Circle...
area_of_circle = PI * (float(C)**2)
# Area of Trapezium...
area_of_trapezium = (1.0 / 2) * (float(A) + float(B)) * float(C)
# Area of Square...
area_of_square = float(B) ** 2
# Area of Rectangle...
area_of_rectangle = float(A)*float(B)

# Printing the results...
print('TRIANGULO: {0:.3f}\nCIRCULO: {1:.3f}\nTRAPEZIO: {2:.3f}\nQUADRADO: {3:.3f}\nRETANGULO: {4:.3f}'.format(
    area_of_triangle, area_of_circle, area_of_trapezium, area_of_square, area_of_rectangle))
