# The formula to calculate the volume is: (4/3) * pi * R3
# Reading the value of Radius...
R = float(input())
PI = 3.14159
# Calculating the value of Sphere...
sphere = (4.0 / 3) * PI * (R ** 3)
# Printing the Result...
print('VOLUME = {0:.3f}'.format(sphere))
